# Generated by Django 5.1.7 on 2025-05-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="study",
            fields=[
                ("study_id", models.IntegerField(primary_key=True, serialize=False)),
                ("close_code", models.CharField(max_length=45)),
                ("invite_code", models.CharField(max_length=45)),
                ("penalty", models.IntegerField()),
                ("sname", models.CharField(max_length=30)),
                ("explanation", models.CharField(max_length=50, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "login_id",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("nickname", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=45)),
                ("comment", models.CharField(max_length=45, null=True)),
                ("status", models.BinaryField(default=1)),
                ("inactivate_date", models.DateTimeField(null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="member",
            fields=[
                ("member_id", models.IntegerField(primary_key=True, serialize=False)),
                ("fail_day", models.IntegerField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(null=True)),
                (
                    "study_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.study"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="study_transaction",
            fields=[
                (
                    "transaction_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("status", models.BinaryField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(null=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="study_image",
            fields=[
                ("image_id", models.IntegerField(primary_key=True, serialize=False)),
                ("image_url", models.CharField(max_length=255)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(null=True)),
                (
                    "transaction_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.study_transaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="study",
            name="manager_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Home.user"
            ),
        ),
    ]
